name: Documentation
description: Documentation request or update for FlightTracker.
title: "[Docs] "
labels:
  - documentation
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear, concise description of the documentation change.
      placeholder: What needs to be documented or updated?
    validations:
      required: true
  - type: checkboxes
    id: layers
    attributes:
      label: Affected Layer(s)
      options:
        - label: Domain
        - label: Application
        - label: Infrastructure
        - label: Presentation - API
        - label: Presentation - Web
        - label: Presentation - Desktop
        - label: Presentation - Mobile
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet list of conditions for completion.
      placeholder: "- Given ..., when ..., then ..."
  - type: textarea
    id: technical
    attributes:
      label: Technical Notes / Proposed Approach
      description: Optional design thoughts, trade-offs, dependencies.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context / Screenshots
      description: Links, images, logs.
