name: Task / Feature / Bug
description: Create a structured issue for FlightTracker development.
title: "[Type] Short description"
labels: []
assignees: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Bug
        - Feature
        - Task
        - Refactor
        - Documentation
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear, concise description of the problem or feature.
      placeholder: What is happening / what do you want to add?
    validations:
      required: true
  - type: checkboxes
    id: layers
    attributes:
      label: Affected Layer(s)
      options:
        - label: Domain
        - label: Application
        - label: Infrastructure
        - label: Presentation - API
        - label: Presentation - Web
        - label: Presentation - Desktop
        - label: Presentation - Mobile
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet list of conditions for completion.
      placeholder: "- Given ..., when ..., then ..."
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps (for bugs)
      description: Exact steps, data, or calls that reproduce the issue.
      placeholder: "1. Go to ...\n2. Click ...\n3. Observe ..."
  - type: textarea
    id: technical
    attributes:
      label: Technical Notes / Proposed Approach
      description: Optional design thoughts, trade-offs, dependencies.
  - type: checkboxes
    id: compliance
    attributes:
      label: Clean Architecture Compliance
      options:
        - label: No new outward dependencies from inner layers
        - label: No EF attributes added to Domain
        - label: Async methods use CancellationToken
        - label: DTOs required for Application -> Presentation boundary
  - type: input
    id: estimate
    attributes:
      label: Estimate (optional)
      placeholder: e.g., 2h, 1d
  - type: textarea
    id: additional
    attributes:
      label: Additional Context / Screenshots
      description: Links, images, logs.
